// Import utility for responsive typography sizing
import { responsiveFontSizes } from '@mui/material';
// Import method to extend MUI's theme using experimental features
import { experimental_extendTheme as extendTheme } from '@mui/material/styles';

// Create a custom MUI theme with color palettes, typography, breakpoints, and component overrides
const theme = extendTheme({
  // Prefix for CSS variables generated by MUI
  cssVarPrefix: 'color',

  // Define color schemes for light mode (dark mode can be added similarly)
  colorSchemes: {
    light: {
      palette: {
        // Background colors used throughout the app
        background: {
          default: '#FFFFFF', // Main background
          light: '#BEBEBA', // Soft grey tone
          light2: '#D3D4D5', // Lighter grey
          light3: '#797979', // Medium grey
          light4: '#0000000A', // Light transparent black
          light5: '#E7E9EC', // Pale grey
          light6: '#FFD8D8D8', // Very light grey, slightly tinted
          light7: '#B0C6E3', // Light blue-grey
          dark: '#383636', // Deep grey
          dark2: '#00000080', // Semi-transparent black
          dark3: '#78787833', // Light transparent grey
          dark4: '#78787866', // Slightly darker transparent grey
          dark5: '#00000099', // More opaque black
          black: '#000000', // Solid black
          black2: '#FF000000', // Fully opaque black in ARGB
        },

        // Primary brand colors
        primary: {
          main: '#436B93', // Primary blue
          light: '#DEECF8', // Soft blue background
          dark: '#284663', // Dark blue
          dark2: '#2D55FF66', // Transparent dark blue
          dark3: '#328899', // Muted cyan-blue
          faded: '#B2BCCA', // Desaturated grey-blue
        },

        // Secondary accent colors
        secondary: {
          main: '#F0CE7F', // Golden yellow
        },

        // Success (positive action) colors
        success: {
          main: '#009900', // Green
          light: '#4ACF48', // Light green
        },

        // Informational colors
        info: {
          main: '#0099CC', // Cyan
          light: '#84C2E2', // Soft blue
        },

        // Warning colors
        warning: {
          dark: '#FFFFC000', // Semi-transparent yellow
          main: '#FFCC33', // Vivid yellow
        },

        // Error/danger colors
        error: {
          main: '#FF0033', // Red
          light: '#FFC7CE', // Pale red-pink
        },

        // Custom "cluster" category (possibly for special UI clusters)
        cluster: {
          main: '#ECDB54', // Mustard yellow
        },
      },
    },
  },

  // Define global typography styles
  typography: {
    fontFamily: 'IBM Plex Sans', // Default font
    fontWeight: 400, // Default weight
    color: '#000000 !important', // Default text color (enforced)

    // Button text: don't transform to uppercase
    button: {
      textTransform: 'none',
    },

    // Heading styles
    h1: { fontWeight: 700, fontSize: '57px' },
    h2: { fontWeight: 700, fontSize: '45px' },
    h3: { fontWeight: 700, fontSize: '36px' },
    h4: { fontWeight: 700, fontSize: '32px' },
    h5: { fontWeight: 700, fontSize: '28px' },
    h6: { fontWeight: 700, fontSize: '24px' },

    // Subtitles
    subtitle1: { fontSize: '22px' },
    subtitle2: { fontSize: '16px' },

    // Body text
    body1: { fontSize: '16px' },
    body2: { fontSize: '14px' },
    body3: { fontSize: '18px', fontWeight: 500 }, // Custom addition, not standard in MUI

    // Captions (typically used for small helper text)
    caption: { fontSize: '12px' },
  },

  // Define responsive breakpoints
  breakpoints: {
    values: {
      xs: 0, // Extra small (mobile)
      sm: 600, // Small devices
      md: 960, // Medium devices/tablets
      lg: 1280, // Large screens
      xl: 1920, // Extra large screens
    },
  },

  // Override styles for specific MUI components
  components: {
    // Toggle button customization
    MuiToggleButton: {
      styleOverrides: {
        root: {
          color: '#FFFFFF', // Default text color
          '&.Mui-selected': {
            color: '#F0CE7F', // Gold color when selected
          },
        },
      },
    },

    // Tab component customization
    MuiTab: {
      styleOverrides: {
        root: {
          '&.Mui-selected': {
            color: '#F0CE7F', // Highlight selected tab in gold
          },
        },
      },
    },
  },
});

// Apply responsive font scaling to the theme (auto scales font sizes based on screen size)
export default responsiveFontSizes(theme);
