// Consortium actions
export const GET_CONSORTIUMS = 'CONSORTIUM/GET_CONSORTIUMS';
export const GET_CONSORTIUMS_SUCCESS = 'CONSORTIUM/GET_CONSORTIUMS_SUCCESS';
export const GET_CONSORTIUMS_FAILURE = 'CONSORTIUM/GET_CONSORTIUMS_FAILURE';
