name: Cypress Tests

on: [push]

env:
  NODE_TLS_REJECT_UNAUTHORIZED: 0

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Yarn install
        run: yarn install

      - name: Generate certificates for next step
        uses: kofemann/action-create-certificate@v0.0.4
        with:
          hostcert: 'hostcert.pem'
          hostkey: 'hostkey.pem'
          cachain: 'ca-chain.pem'

      - name: Use generated certificates
        run: openssl x509 -in hostcert.pem -noout -text

      - name: Create env file
        run: |
          touch .env.development.local
          echo window.env = ${{ secrets.DEV_ENV }} >> .env.development.local
          cat .env.development.local

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: sudo yarn build:local
          browser: chrome
          config-file: cypress.json
          record: true
          spec: cypress/integration/01-Login.spec.js

        env:
          CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
          CYPRESS_EMAIL: ${{ secrets.CYPRESS_EMAIL }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: '@cypress/github-action'
