name: Cypress Tests

on: [push]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Docker build and run
          run: docker build -t transparent-path/react-ui .

  yarn-serve:
    needs: [docker-build]
    runs-on: ubuntu-latest
    steps:
        - name: Yarn install and build
          run: |
            yarn install
            yarn run build:prod
        - name: Yarn serve
          run: yarn serve

  cypress-run:
    needs: [docker-build]
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 60 seconds
        run: sleep 60s
        shell: bash

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          config-file: cypress.json
          record: true
        env:
          CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
          CYPRESS_EMAIL: ${{ secrets.CYPRESS_EMAIL }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
