name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: transparent-path/react-ui:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Yarn install and build
        run: |
          yarn install
          yarn run build:prod

      - name: Docker build
        run: docker build -t transparent-path/react-ui .

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          config-file: cypress.json
          record: true
        env:
          CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
          CYPRESS_EMAIL: ${{ secrets.CYPRESS_EMAIL }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
