name: Cypress Tests

on: [push]

env:
  API_URL: ${{ secrets.API_URL }}
  OAUTH_TOKEN_URL: ${{ secrets.OAUTH_TOKEN_URL }}
  OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
  MAP_API_URL: ${{ secrets.MAP_API_URL }}
  GEO_CODE_API_URL: ${{ secrets.GEO_CODE_API }}
  ALERT_SOCKET_URL: ${{ secrets.ALERT_SOCKET_URL }}
  SESSION_TIMEOUT: ${{ secrets.SESSION_TIMEOUT }}
  HIDE_NOTIFICATIONS: ${{ secrets.HIDE_NOTIFICATIONS }}
  PRODUCTION: ${{ secrets.PRODUCTION }}
  NODE_TLS_REJECT_UNAUTHORIZED: 0

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Yarn install
        run: yarn install

      - name: Generate certificates for next step
        uses: kofemann/action-create-certificate@v0.0.4

        with:
          hostcert: 'hostcert.pem'
          hostkey: 'hostkey.pem'
          cachain: 'ca-chain.pem'

      - name: Use generated certificates
        run: |
          openssl x509 -in hostcert.pem -noout -text

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: sudo yarn https:cypress
          browser: chrome
          config-file: cypress.json
          record: true
          wait-on: 'https://localhost:3000'
          wait-on-timeout: 300
          spec: cypress/integration/01-Login.spec.js

        env:
          CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
          CYPRESS_EMAIL: ${{ secrets.CYPRESS_EMAIL }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: '@cypress/github-action'
          API_URL: ${{ secrets.API_URL }}
