name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: yarn install, build and test
        run: |
          yarn install
          yarn run build:prod

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          config-file: cypress.json
        env:
          USERNAME: ${{ secrets.CYPRESS_USERNAME }}
          PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
          EMAIL: ${{ secrets.CYPRESS_EMAIL }}
