name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the docker-compose stack
        run: docker-compose build

      - name: Setup docker containers
        run: docker-compose up -d

      - name: Check running containers
        run: docker ps -a

      - name: Yarn install and build
        run: docker-compose run --rm --entrypoint 'yarn install && yarn run build:prod' buildly-react-template

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          config-file: cypress.json
          record: true
        env:
          CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
          CYPRESS_EMAIL: ${{ secrets.CYPRESS_EMAIL }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Stop docker container
        run: docker-compose down
