name: Cypress Tests

on: [push]

env:
  API_URL: ${{ secrets.API_URL }}
  OAUTH_TOKEN_URL: ${{ secrets.OAUTH_TOKEN_URL }}
  OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
  MAP_API_URL: ${{ secrets.MAP_API_URL }}
  GEO_CODE_API_URL: ${{ secrets.GEO_CODE_API }}
  ALERT_SOCKET_URL: ${{ secrets.ALERT_SOCKET_URL }}
  SESSION_TIMEOUT: ${{ secrets.SESSION_TIMEOUT }}
  HIDE_NOTIFICATIONS: ${{ secrets.HIDE_NOTIFICATION }}
  PRODUCTION: ${{ secrets.PRODUCTION }}

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Yarn install and build
        run: |
          yarn install
          yarn run build:prod

#      - name: Docker build
#        run: docker build -t transparent-path/react-ui .

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn serve
          browser: chrome
          config-file: cypress.json
          record: true
        env:
          CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
          CYPRESS_EMAIL: ${{ secrets.CYPRESS_EMAIL }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
