name: Build and Push to Demo

on:
  push:
    branches:
      - demo
jobs:
  build:
    name: Build and Push to GCR
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: gcr.io/spry-bricolage-298920/transparent-path/demo/react-ui
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Docker login
      uses: docker/login-action@v2
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCR_JSON_KEY }}

    - name: yarn install, build and test
      run: |
        yarn install
        yarn run build:dev

    - name: Build docker image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Push to Google Container Registry
      run: docker push $IMAGE_NAME:latest
