name: Buildly React Template Unit Test

on:
  push:
    branches:
      - prod

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: yarn install, build and test
      run: |
          yarn install
          yarn run build:prod
          yarn test:prod